export { default as Icon } from "./Icon"
export { default as Navbar } from "./navbar"
export { default as Login } from "./loginComp"
export { default as SignUp } from "./signUpComp"
export { default as ForgotPassComp } from "./forgotPassComp"
export { default as ResetPassComp } from "./resetPassComp"
export { default as VerifyOtpComp } from "./verifyOtpComp"